name: Code Coverage

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - 'scripts/**'
      - 'example/**'

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "yarn"

      - name: Yarn Install
        run: yarn install

      - name: Run Coverage
        run: yarn -s run coverage

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
