name: Create Release

on:
  push:
    tags:
      - "v*"

jobs:
  tagged_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "yarn"
          registry-url: "https://registry.npmjs.org"
          scope: "@synapseprotocol"

      - name: Yarn Install
        run: yarn install

      - name: Yarn Build
        run: yarn run build

      - name: Make tarball
        run: |
          mkdir -p ./artifacts
          yarn pack --filename "./artifacts/synapseprotocol-sdk-$(git describe --tags --abbrev=0).tgz"

      - name: Create release with tarball
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            "./artifacts/synapseprotocol-sdk-$(git describe --tags --abbrev=0).tgz"