name: Tests

on:
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
      - reopened
  push:
    branches:
      - master
      - dev
    paths-ignore:
      - 'README.md'
      - 'CONTRIBUTING.md'
      - 'LICENSE'
      - '.gitignore'
      - 'scripts/**'
      - 'examples/**'

jobs:
  test:
    strategy:
      matrix:
        node-version:
          - 16
          - 17
        platform:
          - ubuntu-latest

    if: ${{ !contains(toJSON(github.event.commits.*.message), '[ci notest]') }}

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Yarn Install
        run: yarn install

      - name: Run Tests
        run: yarn -s run test:coverage
        env:
          REPORTS_DIR: ${{ github.workspace }}/coverage
          RPC_BATCH_WAIT_TIME_MS: 100
          HARMONY_RPC_URI:  "https://api.fuzz.fi/"
          ETH_RPC_URI:       ${{ secrets.ETHEREUM_RPC_URI }}
          POLYGON_RPC_URI:   ${{ secrets.POLYGON_RPC_URI }}
          MOONRIVER_RPC_URI: ${{ secrets.MOONRIVER_RPC_URI }}
          INFINITE_APPROVALS_PRIVKEY:          ${{ secrets.INFINITE_APPROVALS_PRIVKEY }}
          INFINITE_APPROVALS_PRIVKEY_ADDRESS:  ${{ secrets.INFINITE_APPROVALS_PRIVKEY_ADDRESS }}
          BRIDGE_INTERACTIONS_PRIVKEY:         ${{ secrets.BRIDGE_INTERACTIONS_PRIVKEY }}
          BRIDGE_INTERACTIONS_PRIVKEY_ADDRESS: ${{ secrets.BRIDGE_INTERACTIONS_PRIVKEY_ADDRESS }}

      - name: Coverage report
        run: yarn -s run coverage:report
        env:
          REPORTS_DIR: ${{ github.workspace }}/coverage

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ${{ github.workspace }}/coverage/lcov.info
          flag-name: node-v${{ matrix.node-version }}