name: Tests

on:
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
      - reopened
  push:
    branches:
      - master
      - dev
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - 'scripts/**'
      - 'example/**'

jobs:
  test:
    strategy:
      matrix:
        node-version:
          - 16
          - 17
        platform:
          - ubuntu-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Yarn Install
        run: yarn install

      - name: Run Tests
        run: yarn -s run test:coverage
        env:
          REPORTS_DIR: ${{ github.workspace }}/coverage

      - name: Coverage report
        run: yarn -s run coverage:report
        env:
          REPORTS_DIR: ${{ github.workspace }}/coverage

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ${{ github.workspace }}/coverage/lcov.info
          flag-name: node-v${{ matrix.node-version }}