name: Tests

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - master
      - dev
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.nvmrc'
      - '.gitignore'
      - '.yarnclean'
      - 'scripts/**'
      - 'examples/**'
      - 'tsconfig.build.json'

  push:
    branches:
      - master
      - dev
      - 'renovate/*'
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.nvmrc'
      - '.gitignore'
      - '.yarnclean'
      - 'scripts/**'
      - 'examples/**'
      - 'tsconfig.build.json'

jobs:
  test:
    strategy:
      matrix:
        node-version:
          - 16
          - 17
        platform:
          - ubuntu-latest

    if: ${{ !contains(toJSON(github.event.commits.*.message), '[ci notest]') }}

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - run: yarn install

      - name: Run Tests (Node v${{ matrix.node-version }})
        run: yarn -s run test:coverage
        env:
          REPORTS_DIR: ${{ github.workspace }}/coverage
          RPC_BATCH_WAIT_TIME_MS: 75
          HARMONY_RPC_URI:   "https://api.fuzz.fi/"
          ETH_RPC_URI:       ${{ secrets.ETHEREUM_RPC_URI }}
          POLYGON_RPC_URI:   ${{ secrets.POLYGON_RPC_URI }}
          INFINITE_APPROVALS_PRIVKEY:          ${{ secrets.INFINITE_APPROVALS_PRIVKEY }}
          INFINITE_APPROVALS_PRIVKEY_ADDRESS:  ${{ secrets.INFINITE_APPROVALS_PRIVKEY_ADDRESS }}
          BRIDGE_INTERACTIONS_PRIVKEY:         ${{ secrets.BRIDGE_INTERACTIONS_PRIVKEY }}
          BRIDGE_INTERACTIONS_PRIVKEY_ADDRESS: ${{ secrets.BRIDGE_INTERACTIONS_PRIVKEY_ADDRESS }}

      - name: Generate Coverage report
        run: yarn -s run coverage:report
        env:
          REPORTS_DIR: ${{ github.workspace }}/coverage

      - name: Coveralls - Process coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ${{ github.workspace }}/coverage/lcov.info
          flag-name:    node-v${{ matrix.node-version }}
          parallel:     true

  send-coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls - Process all coverage results
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
